### ISSUE TITLE
Table prefix

### ISSUE THREAD

**Issue by joancifo** [Jimbolino/laravel-model-builder#1]
Nice job!

I detected a minor problem. I think if a prefix is defined, the models should be created without the prefix.

Great plugin.

**Comment by Jimbolino** [comment]
I had this feature in an earlier version, but decided to take it out later.
You can still easily activate it by changing setting $removePrefix = true, here:
https://github.com/Jimbolino/laravel-model-builder/blob/master/src/StringUtils.php#L27

Removing table prefixes from your model names will be problematic when you have 2 tables with similar names.
For example my database had a "us_group" and "pr_group" table. Which resulted in only the 2nd model being written.

**Comment by joancifo** [comment]
Thank you for your answer.

When I said 'prefix' I was thinking in 'prefix' field of 'connections' of /app/config/database.php (L5).

**Comment by Jimbolino** [comment]
Ok, the documentation is not really descriptive about this one.
I found i can request the current prefix with DB::getTablePrefix();
Correct me if I'm wrong but i assume the following is true:
- $table should not contain the prefix
- the model ClassName should also not contain the prefix
- i should limit the generator so that all tables without the prefix are being ignored.

**Comment by joancifo** [comment]
Nice!

Well, the first point I think it should be "$table should not _start_ with the prefix"
And then, the ClassName should be the table name without the prefix.
I agree with third point!

Anyway, this is only my opinion; you did a fantastic job!

**Comment by Jimbolino** [comment]
it should be fixed in the latest version: https://github.com/Jimbolino/laravel-model-builder/commit/901bf10c3ce4fe0056a8673db0a7a20c0f2eb401
